name: C/C++ CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gdb
          version: 1.0
    - name: make
      working-directory: ./
      run: sh make_test.sh
    - name: run
      working-directory: ./
      run: cat test/gdb_commands.txt | gdb test/rb 2>&1 | python3 test/check.py
